name:                csv-challenge
version:             0.1.0.0
github:              "githubuser/csv-challenge"
license:             BSD3
author:              "Dev Madupuri"
maintainer:          "dmaxplanck@gmail.com"
copyright:           "2022 Dev Madupuri"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Dev-m8/csv-challenge#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- aeson
- cassava
- containers
- vector
- directory
default-extensions:
- OverloadedStrings
- DeriveGeneric

library:
  source-dirs: src

executables:
  csv-challenge-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csv-challenge
    default-extensions:
    - OverloadedStrings
    - DeriveGeneric

tests:
  csv-challenge-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csv-challenge
    - hspec
